// <auto-generated />
namespace EAD_Assignment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class init_again : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init_again));
        
        string IMigrationMetadata.Id
        {
            get { return "202205080828558_init_again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
